<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KR5LUKG" failures="0" tests="3" name="myselenium1.sample31" time="2.045" errors="1" timestamp="2024-04-30T10:51:39 IST" skipped="1">
  <testcase classname="myselenium1.sample31" name="m4" time="0.024">
    <system-out>
      <![CDATA[running m4]]>
    </system-out>
  </testcase> <!-- m4 -->
  <testcase classname="myselenium1.sample31" name="m6" time="0.001">
    <skipped/>
  </testcase> <!-- m6 -->
  <testcase classname="myselenium1.sample31" name="m5" time="2.020">
    <error message="Method myselenium1.sample31.m5() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method myselenium1.sample31.m5() didn't finish within the time-out 2000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at myselenium1.sample31.m5(sample31.java:13)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- m5 -->
  <system-out>
    <![CDATA[running m4]]>
  </system-out>
</testsuite> <!-- myselenium1.sample31 -->
